.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "CFN\-TOOL\-TRANSFORM" "1" "April 2021" "CloudFormation Tools 5.0.1" "CloudFormation Tools"
.
.SH "NAME"
\fBcfn\-tool\-transform\fR \- expand template macros
.
.SH "SYNOPSIS"
\fBcfn\-tool\fR \fBtransform\fR [\fIOPTIONS\fR\.\.\.] \fITEMPLATE\-FILE\fR
.
.SH "DESCRIPTION"
Expands macros in the \fITEMPLATE\-FILE\fR, optionally passing the resulting YAML through a linter, prints it to \fBstdout\fR, and exits\. No nested templates are processed, no packages are prepared, no validation is performed, and no stack is deployed\. This can be useful for debugging\.
.
.SH "OPTIONS"
The \fBtransform\fR command accepts the following options:
.
.TP
\fB\-l\fR, \fB\-\-linter\fR=\fICOMMAND\fR
Run \fICOMMAND\fR on each processed template file, aborting if the \fICOMMAND\fR fails\. The template file path is appended to the \fICOMMAND\fR string and the resulting command line is evaluated in the \fBbash\fR(1) shell (see the \fBEXAMPLES\fR section below)\. The \fICOMMAND\fR is executed with its working directory set to the current directory (ie\. the directory in which the \fBcfn\-tool\fR program runs)\.
.
.TP
\fB\-p\fR, \fB\-\-profile\fR=\fINAME\fR
Use the AWS profile given by \fINAME\fR to configure the AWS credentials provider chain\. When this option is specified the \fINAME\fR is propagated to child processes via the \fBAWS_PROFILE\fR environment variable (eg\. when the \fBaws\fR(1) tool is called from a template)\.
.
.TP
\fB\-q\fR, \fB\-\-quiet\fR
Suppress all informational, diagnostic, and warning output\.
.
.TP
\fB\-r\fR, \fB\-\-region\fR=\fINAME\fR
Use the AWS region given by \fINAME\fR for all AWS API calls\. When this option is specified the \fINAME\fR is propagated to child processes via the \fBAWS_REGION\fR and \fBAWS_DEFAULT_REGION\fR environment variables (eg\. when the \fBaws\fR(1) tool is called from a template)\.
.
.TP
\fB\-v\fR, \fB\-\-verbose\fR
Print extra diagnostic output while processing\.
.
.SH "EXAMPLES"
Transform the template \fIinfra/my\-template\.yml\fR, lint it with \fBcfn\-lint\fR(1), and print the result to \fBstdout\fR:
.
.IP "" 4
.
.nf

cfn\-tool transform \-\-linter "cfn\-lint \-f pretty" infra/my\-template\.yml
.
.fi
.
.IP "" 0
.
.SH "EXIT STATUS"
Exits with a status of 1 if an error occurred, or 0 otherwise\.
.
.SH "BUGS"
Please open an issue: \fIhttps://github\.com/daggerml/cfn\-tool/issues\fR\.
.
.SH "SEE ALSO"
Man pages for other commands:
.
.IP "\(bu" 4
\fBcfn\-tool\fR(1)
.
.IP "\(bu" 4
\fBcfn\-tool\-deploy\fR(1)
.
.IP "\(bu" 4
\fBcfn\-tool\-update\fR(1)
.
.IP "" 0
.
.P
Documentation for built\-in macros:
.
.IP "\(bu" 4
\fBcfn\-tool\-macros\fR(7)
.
.IP "" 0
.
.SH "COPYRIGHT"
Copyright © 2021 Micha Niskin \fB<micha\.niskin@gmail\.com>\fR, distributed under the following license:
.
.IP "\(bu" 4
\fIhttps://raw\.githubusercontent\.com/daggerml/cfn\-tool/5\.0\.1/LICENSE\fR
.
.IP "" 0
.
.P
THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT\. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE\.
