.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "CFN\-TOOL" "1" "August 2021" "CloudFormation Tools 5.7.4" "CloudFormation Tools"
.
.SH "NAME"
\fBcfn\-tool\fR \- extra tools for working with aws cloudformation
.
.SH "SYNOPSIS"
\fBcfn\-tool\fR [\fB\-h\fR|\fB\-\-help\fR|\fB\-V\fR|\fB\-\-version\fR]
.
.br
\fBcfn\-tool\fR \fICOMMAND\fR [\fIOPTIONS\fR\.\.\.] [\fIARGUMENTS\fR\.\.\.]
.
.SH "DESCRIPTION"
This program provides extra tools for working with AWS CloudFormation including a template macro preprocessor, resource packaging, extended support for nested stacks, additional stack deployment options (like template linting, for example), and more\.
.
.P
The macro preprocessor provides a variety of generally useful, built\-in macros to handle common use cases, and can be extended via JavaScript modules loaded at macro expansion time (see \fBcfn\-tool\-macros\fR(7) for details)\.
.
.SH "COMMANDS"
The first argument to \fBcfn\-tool\fR is the \fICOMMAND\fR\. Each command has its own set of options and required positional parameters, as described in its manual page\.
.
.SH "BASH COMPLETION"
Add the following to your \fBbash\fR(1) configuration:
.
.IP "" 4
.
.nf

complete \-o default \-C $(which cfn\-tool\-completer) cfn\-tool
.
.fi
.
.IP "" 0
.
.SH "BUGS"
Please open an issue: \fIhttps://github\.com/daggerml/cfn\-tool/issues\fR\.
.
.SH "SEE ALSO"
Each command has its own man page:
.
.IP "\(bu" 4
\fBcfn\-tool\-deploy\fR(1)
.
.IP "\(bu" 4
\fBcfn\-tool\-transform\fR(1)
.
.IP "\(bu" 4
\fBcfn\-tool\-update\fR(1)
.
.IP "" 0
.
.P
Documentation for built\-in macros:
.
.IP "\(bu" 4
\fBcfn\-tool\-macros\fR(7)
.
.IP "" 0
.
.SH "COPYRIGHT"
Copyright © 2021 Micha Niskin \fB<micha\.niskin@gmail\.com>\fR, distributed under the following license:
.
.IP "\(bu" 4
\fIhttps://raw\.githubusercontent\.com/daggerml/cfn\-tool/5\.7\.4/LICENSE\fR
.
.IP "" 0
.
.P
THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT\. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE\.
