.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "CFN\-TOOL" "1" "March 2021" "" "CloudFormation Tools"
.
.SH "NAME"
\fBcfn\-tool\fR \- cloudformation template process and stack deploy
.
.SH "SYNOPSIS"
\fBcfn\-tool\fR [\fB\-h\fR|\fB\-\-help\fR]
.
.br
\fBcfn\-tool\fR \fBtransform\fR [\fIoptions\fR\.\.\.] \fItemplate\-file\fR
.
.br
\fBcfn\-tool\fR \fBdeploy\fR [\fIoptions\fR\.\.\.] \fItemplate\-file\fR [\fIstack\-name\fR]
.
.SH "COMMANDS"
The first argument to \fBcfn\-tool\fR is the \fBcommand\fR \(em each command performs an operation and has its own set of options specified by subsequent arguments\.
.
.SS "transform"
Given a \fItemplate\-file\fR, expands macros in the template and prints the result YAML to stdout\.
.
.P
Options:
.
.TP
\fB\-q\fR, \fB\-\-quiet\fR
Suppress all diagnostic output and warnings\.
.
.TP
\fB\-v\fR, \fB\-\-verbose\fR
Print diagnostic output while processing\.
.
.SS "deploy"
Deploys \fItemplate\-file\fR to the cloudformation stack \fIstack\-name\fR\. If no stack named \fIstack\-name\fR exists one is be created\. Otherwise the existing stack is updated\.
.
.P
When no \fIstack\-name\fR is specified a dry run is performed, where all templates are transformed, packaged, linted, and validated, but no templates or packages are uploaded to S3 and no stack is created or updated\.
.
.P
Options:
.
.TP
\fB\-b\fR, \fB\-\-bucket\fR=\fIname\fR
Upload templates to the S3 bucket given by \fIname\fR\. This option overrides the \fBCFN_TOOL_BUCKET\fR environment variable\. (See the \fBENVIRONMENT\fR section below\.)
.
.TP
\fB\-l\fR, \fB\-\-linter\fR=\fIcommand\fR
Run \fIcommand\fR on each processed template, aborting if the \fIcommand\fR fails\. The template file path will be appended to the \fIcommand\fR and run in \fBbash\fR(1)\. Paths are relative to the directory in which the \fBcfn\-tool\fR program is run\.
.
.TP
\fB\-P\fR, \fB\-\-parameters\fR=\fIkey\fR=\fIvalue\fR[,\fIkey\fR=\fI<value\fR,\.\.\.]
Set template input parameter overrides\. When updating an existing stack the values of any unspecified parameters will be preserved\.
.
.TP
\fB\-p\fR, \fB\-\-profile\fR=\fIname\fR
Use the AWS profile given by \fIname\fR\. This option overrides the \fBAWS_ACCESS_KEY_ID\fR and \fBAWS_SECRET_ACCESS_KEY\fR environment variables\. (See the \fBENVIRONMENT\fR section below\.)
.
.TP
\fB\-q\fR, \fB\-\-quiet\fR
Suppress all diagnostic output and warnings\.
.
.TP
\fB\-r\fR, \fB\-\-region\fR=\fIname\fR
Use the AWS region given by \fIname\fR\. This option overrides the \fBAWS_REGION\fR and \fBAWS_DEFAULT_REGION\fR environment variables\. (See the \fBENVIRONMENT\fR section below\.)
.
.TP
\fB\-t\fR, \fB\-\-tags\fR=\fIkey\fR=\fIvalue\fR[,\fIkey\fR=\fI<value\fR,\.\.\.]
A list of tags to associate with the stack that is created or updated\. AWS CloudFormation also propagates these tags to resources in the stack if the resource supports it\.
.
.TP
\fB\-v\fR, \fB\-\-verbose\fR
Print diagnostic output while processing\.
.
.SH "ENVIRONMENT"
The following environment variables may be used in lieu of the \fB\-\-profile\fR and \fB\-\-region\fR options to configure the AWS credentials provider chain\.
.
.TP
\fBAWS_DEFAULT_REGION\fR, \fBAWS_REGION\fR
The AWS region\. These variables are set automatically when the \fB\-\-region\fR option is specified\. Either of the above can be set in the environment when the \fB\-\-region\fR option is not specified (there are two because of an inconsistency between the AWS CLI tools and the provider chain in the AWS SDK, sometimes you need the one, sometimes the other \-\- the tool will copy whichever one you set to the other one)\.
.
.TP
\fBAWS_ACCESS_KEY_ID\fR
The AWS access key identifier (ie\. \'AKIAXXXXXXXXXXXXXXXX\')\.
.
.TP
\fBAWS_SECRET_ACCESS_KEY\fR
The AWS secret key\.
.
.P
Additionally, the following environment variables may be used to configure the program\.
.
.TP
\fBCFN_TOOL_BUCKET\fR
The name of the S3 bucket to which template files and packages will be uploaded\. Overridden by the \fB\-b\fR, \fB\-\-bucket\fR option (see \fBdeploy\fR above)\.
.
.SH "EXIT STATUS"
Exits with a status of 1 if an error occurred, or 0 otherwise\.
