// Generated by CoffeeScript 2.5.1
(function() {
  var CfnExit;

  CfnExit = class CfnExit extends Error {
    constructor(status) {
      super("exit");
      this.status = status;
      this.name = 'CfnExit';
    }

  };

  module.exports = CfnExit;

}).call(this);

//# sourceMappingURL=CfnExit.js.map
