// Generated by CoffeeScript 2.5.1
(function() {
  var CfnError;

  CfnError = class CfnError extends Error {
    constructor(message, body, aborting) {
      super(message);
      this.body = body;
      this.aborting = aborting;
      this.name = 'CfnError';
    }

  };

  module.exports = CfnError;

}).call(this);

//# sourceMappingURL=CfnError.js.map
