// Generated by CoffeeScript 2.5.1
(function() {
  var exec, file, fn, list, none, prefixFilter, profile, region;

  fn = require('./fn');

  prefixFilter = function(prefix, xs) {
    return xs.filter(function(x) {
      return x && ((!prefix) || x.startsWith(prefix));
    }).join('\n');
  };

  exec = function(cmd) {
    var e;
    try {
      return fn.execShell(cmd).trimRight();
    } catch (error) {
      e = error;
    }
  };

  none = module.exports.none = function(prefix) {};

  file = module.exports.file = function(prefix) {
    return exec(`compgen -f '${prefix}'`);
  };

  list = module.exports.list = function(prefix, words) {
    return prefixFilter(prefix, words);
  };

  profile = module.exports.profile = function(prefix) {
    return prefixFilter(prefix, exec('aws configure list-profiles').split('\n'));
  };

  region = module.exports.region = function(prefix) {
    return list(prefix, ['ap-south-1', 'eu-west-2', 'eu-west-1', 'ap-northeast-2', 'ap-northeast-1', 'sa-east-1', 'ca-central-1', 'ap-southeast-1', 'ap-southeast-2', 'eu-central-1', 'us-east-1', 'us-east-2', 'us-west-1', 'us-west-2']);
  };

}).call(this);

//# sourceMappingURL=completions.js.map
