// Generated by CoffeeScript 2.5.1
(function() {
  var MESSAGE, basename, colors, createLogger, format, priority, prog, stderr, transports;

  ({createLogger, format, transports} = require('winston'));

  ({stderr} = require('chalk'));

  ({MESSAGE} = require('triple-beam'));

  ({basename} = require('path'));

  prog = basename(process.argv[1] || 'repl');

  colors = {
    error: stderr.red,
    warn: stderr.yellow,
    info: stderr,
    http: stderr,
    verbose: stderr,
    debug: stderr,
    silly: stderr
  };

  priority = {
    error: 0,
    warn: 1,
    info: 2,
    http: 3,
    verbose: 4,
    debug: 5,
    silly: 6
  };

  format = (format(function(info, opts) {
    var body, color, lines, message1, message2, verbose;
    color = colors[info.level];
    verbose = priority[module.exports.level] > priority.info || priority[info.level] < priority.info;
    lines = info.message.split('\n').map(function(x) {
      return x.trimRight();
    }).filter(function(x) {
      return x;
    });
    message1 = color.bold(`${prog}: ${lines.shift()}`);
    if (lines.length) {
      message2 = color(lines.join('\n'));
    }
    if (info.body && verbose) {
      body = stderr.dim(info.body);
    }
    info[MESSAGE] = [message1, message2, body].filter(function(x) {
      return x;
    }).join('\n');
    return info;
  }))();

  transports = [
    new transports.Console({
      stderrLevels: ['error',
    'warn',
    'info',
    'http',
    'verbose',
    'debug',
    'silly']
    })
  ];

  module.exports = createLogger({format, transports});

}).call(this);
